---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patch-route
  namespace: eda
  labels:
    app: patch-route
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"