---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: set-resource-quota-on-namespace
  namespace: eda
  labels:
    app: set-resource-quota-on-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"