---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: patch-route
  namespace: eda
  labels:
    app: patch-route
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patch-route
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: patch-route  
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: patch-route
          image: 'quay.io/ansible/ansible-rulebook:v0.12.0'
          workingDir: /mnt
          command:
            - /bin/bash
            - '-c'
            - |
              wget -P /tmp https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.13.0-rc.0/openshift-client-linux.tar.gz
              tar zxvf /tmp/openshift-client-linux.tar.gz -C /opt/app-root/bin/
              pip3 install -r requirements.txt
              ansible-galaxy collection install -r requirements.yml
              oc login --token=${OCP_TOKEN} --server=${OCP_API_URL} --certificate-authority=certificate/ca.crt 
              ansible-rulebook -i inventory --rulebook exercise2-rulebook.yml --verbose --controller-url ${AC_WEB_URL} --controller-token ${AC_TOKEN}
          volumeMounts:
            - name: config-volume
              mountPath: /mnt
            - name: kube-root-ca
              mountPath: /mnt/certificate/
          env:
            - name: OCP_API_URL
              valueFrom:
                secretKeyRef: 
                  name: openshift-api
                  key: openshift_api_url
            - name: OCP_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: openshift-api
                  key: openshift_bearer_token
            - name: AC_WEB_URL
              valueFrom:
                secretKeyRef: 
                  name: automation-controller
                  key: aap_controller_web_url
            - name: AC_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: automation-controller
                  key: aap_controller_token
          securityContext:
            allowPrivilegeEscalation: true
      serviceAccount: eda-user
      volumes:
        - name: config-volume
          configMap:
            name: patch-route
        - name: kube-root-ca
          configMap:
            name: kube-root-ca.crt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

