---
kind: ConfigMap
apiVersion: v1
metadata:
  name: resource-quota
  namespace: eda
immutable: false
data:
  exercise3-rulebook.yml: |-
    ---
    - name: Listen for newly created Namespace
      hosts: all
      sources:
        - sabre1041.eda.k8s:
            api_version: v1
            kind: Namespace
      rules:
        - name: Set Resource Quotas to a Namespace
          condition: event.type == "ADDED"
          action:
            run_job_template:
              name: EDA-OpenShift-Exercise3
              organization: Default

  inventory: |-
    localhost
    [all:vars]
    ansible_python_interpreter=/opt/app-root/bin/python

  requirements.yml: |-
    collections:
      - name: sabre1041.eda
        version: 1.0.0

  requirements.txt: |-
    kubernetes==26.1.0
    requests==2.28.2