---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: create-snapshot
  namespace: eda
  labels:
    app: create-snapshot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: create-snapshot
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: create-snapshot  
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: create-snapshot
          image: 'quay.io/ansible/ansible-rulebook:v0.12.0'
          workingDir: /mnt
          command:
            - /bin/bash
            - '-c'
            - |
              echo "################# Download oc cli ####################"
              wget -P /tmp https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.13.0-rc.0/openshift-client-linux.tar.gz
              tar zxvf /tmp/openshift-client-linux.tar.gz -C /opt/app-root/bin/
              echo "################# Install python dependencies ####################"
              pip3 install -r requirements.txt
              echo "################# Install ansible collection ####################"
              ansible-galaxy collection install -r requirements.yml
              echo "################# Login OpenShift ####################"
              oc login -u ${OCP_USER_NAME} -p ${OCP_USER_PASSWORD} --server=${OCP_API_URL} --certificate-authority=certificate/ca.crt 
              echo "################# Run ansible rulebook ####################"
              ansible-rulebook -i inventory --rulebook exercise1-rulebook.yml --verbose --controller-url ${AC_WEB_URL} --controller-token ${AC_TOKEN}
          volumeMounts:
            - name: config-volume
              mountPath: /mnt
            - name: kube-root-ca
              mountPath: /mnt/certificate/
          env:
            - name: OCP_API_URL
              valueFrom:
                secretKeyRef: 
                  name: openshift-api
                  key: openshift_api_url
            - name: OCP_USER_NAME
              valueFrom:
                secretKeyRef: 
                  name: openshift-api
                  key: openshift_user_name
            - name: OCP_USER_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: openshift-api
                  key: openshift_user_password
            - name: AC_WEB_URL
              valueFrom:
                secretKeyRef: 
                  name: automation-controller
                  key: aap_controller_web_url
            - name: AC_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: automation-controller
                  key: aap_controller_token
          securityContext:
            allowPrivilegeEscalation: true
      serviceAccount: eda-sa
      volumes:
        - name: config-volume
          configMap:
            name: create-snapshot
        - name: kube-root-ca
          configMap:
            name: kube-root-ca.crt
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

